### PR TITLE
Add SDMX Dashboard Generator Repository to software.yaml

### PR DESCRIPTION
**Pull request by osirello**
## Description

This pull request adds the SDMX Dashboard Generator to the `data/software.yaml` file. 

### Changes Made:
- Added the SDMX Dashboard Generator repository information to the `software.yaml` file.
- Included the repository URL, description, and other relevant details.

### Checklist:
- [X] Added SDMX Dashboard Generator repository details to `software.yaml`.
- [X] Ensured correctness of repository URL and description.

## About SDMX Dashboard Generator
The SDMX Dashboard Generator (SDMX-DG) is an open-source [Dash](https://dash.plotly.com/) application that generates dynamic dashboards by pulling data and metadata from SDMX Rest API. It supports the version 2.1 of the standard. It leverages the open-source library SDMXthon to retrieve and parse data and metadata in SDMX. Data and metadata are supported by asynchronous retrieval. A dashboard is composed of several visualizations as defined by the specifications provided in a .yaml file. 
The specifications are interpreted by a ChartGenerator class containing instructions to define the Plotly charts. It has been developed for the [SDMX Hackathon Global Conference 2023](https://www.sdmx2023.org/hackathon).

### Documentation
A quick introduction to the SDMX Dashboard Generator is available at [sdmx.io](https://www.sdmx.io/tools/sdmx-dg/). The full documentation for this app is available at [GitHub Pages](https://bis-med-it.github.io/SDMX-dashboard-generator/).

### CODE REVIEW

**Comment by olavtenbosch** [comment]
Dear Osirello, 
Thanks for the PR, certainly a useful generic application on offstats!
What I miss in the docs is a link to a minimum working example and preferably one to an instance in production.
Would it be possible to add such?
Thanks, Olav

**Comment by olavtenbosch** [comment]
Yes, I have seen that, its good.

But for a potential user it would be even easier if there's also a link to a running instance, to easily get a feeling which dashboard functionality is provided. No install, just a link.
Also, this would show that the dashboard generator has been used somewhere in production?

**Comment by osirello** [comment]
Dear Olav,

we use the dashboard generator in production internally but we release only the code externally (as for any other Dash application). I hope this helps.

Thank you very much for your consideration.

**Comment by olavtenbosch** [comment]
Thanks, that explains.
In that case it qualifies for the list, I will add it soon, thanks again for notifying me!

Regards, Olav

**Comment by olavtenbosch** [comment]
It's on the list now.
The OSS license couldn't be deduced by GH BTW, I guess because you use a more complicated setting than usual, if it bothers you you could have a look how GH could recognise your situation into one of the standard license situations.

**Pull request merged**
